name: 'Online signing of targets'
description: 'TUF-on-CI Online signer for targets'

# This action is not called from any standard workflows.
# To use this, create custom workflow that triggers this action when
# needed. This is typically done for delegations, that would be
# triggered based on a change to the delegation metadata file.

inputs:
  token:
    description: 'GitHub token'
    required: true
  targets_to_sign:
    description: "whitespace separated list of targets role names that should be signed with KMS"
    required: false
    default: ""
  gcp_workload_identity_provider:
    description: "Google Cloud workload identity provider (required if GCP is used to sign targets roles)"
    required: false
    default: ""
  gcp_service_account:
    description: "Google Cloud service account name (required if GCP is used to sign targets roles)"
    required: false
    default: ""
  aws_region:
    description: "AWS region"
    required: false
    default: ""
  aws_role_to_assume:
    description: "AWS role to assume"
    required: false
    default: ""
  azure_client_id:
    description: "Azure SPN client id (required to use Azure to sign target roles)"
    required: false
    default: ""
  azure_tenant_id:
    description: "Azure SPN tenant id (required to use Azure to sign target roles)"
    required: false
    default: ""
  azure_subscription_id:
    description: "Azure SPN subscription id (required to use Azure to sign target roles)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        token: ${{ inputs.token }}
        fetch-depth: 0
        persist-credentials: true

    - name: Authenticate to Google Cloud
      if: inputs.gcp_workload_identity_provider != ''
      uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
      with:
        token_format: access_token
        workload_identity_provider: ${{ inputs.gcp_workload_identity_provider }}
        service_account: ${{ inputs.gcp_service_account }}

    - name: Authenticate to AWS
      if: inputs.aws_role_to_assume != ''
      uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c #v6.2.3
      with:
        aws-region: ${{ inputs.aws_region }}
        role-to-assume: ${{ inputs.aws_role_to_assume }}

    - name: Authenticate to Azure cloud
      if: inputs.azure_client_id != ''
      uses: azure/login@f5d393ae46f8fde4be8b75f32e3fc50e654ad0ca # v3.0.1
      with:
        client-id: ${{ inputs.azure_client_id }}
        tenant-id: ${{ inputs.azure_tenant_id }}
        subscription-id: ${{ inputs.azure_subscription_id }}

    - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      with:
        enable-cache: false
        python-version: "3.14"
        version-file: ${{ github.action_path }}/../../uv.lock

    - run: | # zizmor: ignore[github-env]
        echo "::group::Install tuf-on-ci"
        cd $GITHUB_ACTION_PATH/../../repo
        UV_PROJECT_ENVIRONMENT=$GITHUB_WORKSPACE/.venv uv sync --frozen --no-dev
        echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH
        echo "::endgroup::"
      shell: bash

    - id: sign_targets
      if: inputs.targets_to_sign != ''
      env:
        TARGETS_TO_SIGN: ${{ inputs.targets_to_sign }}
      run: |
        if tuf-on-ci-online-sign-targets $TARGETS_TO_SIGN >> sign-output;  then
          echo "targets_signed=true" >> $GITHUB_OUTPUT
        else
          echo "targets_signed=false" >> $GITHUB_OUTPUT
        fi
        cat sign-output
        cat sign-output >> output
        cat sign-output >> "$GITHUB_STEP_SUMMARY"
      shell: bash

    - name: Dispatch another signing event workflow
      # dispatch if using default token: otherwise update_targets step
      # has alreaddy triggered a push event
      if: inputs.token == github.token && steps.sign_targets.outputs.targets_signed == 'true'
      uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
      with:
        github-token: ${{ inputs.token }}
        script: |
          console.log('Dispatching another signing event workflow after a targets metadata update')
          github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'signing-event.yml',
            ref: process.env.GITHUB_REF_NAME,
          })
