version: 2
updates:

- package-ecosystem: "pip"
  directory: "/build"
  schedule:
    interval: "weekly"
  cooldown:
    default-days: 7
  groups:
    build-dependencies:
      # Critical build/release dependencies constrained in build/build-constraints.txt
      patterns:
        - "*"

- package-ecosystem: "pip"
  directories:
    - "/signer"
    - "/repo"
    - "/actions"
  schedule:
    interval: "weekly"
  cooldown:
    default-days: 7
  groups:
    pinned-test-dependencies:
      # Dependencies pinned to ensure test reproducibility
      patterns:
        - "mypy"
        - "ruff"
        - "zizmor"
    minimum-runtime-dependencies:
      # Runtime dependency ranges set in {signer,repo}/pyproject.toml
      patterns:
        - "*"

- package-ecosystem: "github-actions"
  directories:  
    - "/"
    - "/actions/create-signing-events/"
    - "/actions/online-sign/"
    - "/actions/signing-event/"
    - "/actions/test-repository/"
    - "/actions/update-issue/"
    - "/actions/upload-repository/"
  schedule:
    interval: "weekly"
  cooldown:
    default-days: 7
  groups:
    actions-dependencies:
      patterns:
        - "*"
