[tox]
env_list = lint-signer, lint-repo, lint-actions, test-repo, test-signer, test-e2e
skipsdist = true

[testenv]
runner = uv-venv-lock-runner
uv_sync_flags = --frozen

[testenv:lint-signer]
description = Signer Linting
labels = lint
uv_sync_flags = --package, tuf-on-ci-sign, --frozen
dependency_groups = dev
changedir = signer
commands =
    ruff check .
    ruff format --check --diff .
    mypy .

[testenv:lint-repo]
description = Repository Linting
labels = lint
uv_sync_flags = --package, tuf-on-ci, --frozen
dependency_groups = dev
changedir = repo
commands =
    ruff check .
    ruff format --check --diff .
    mypy .

[testenv:lint-actions]
description = Actions Linting
labels = lint
uv_sync_flags = --package, tuf-on-ci, --frozen
dependency_groups = dev
commands =
    zizmor .

[testenv:test-repo]
description = Repository unit tests
labels = test
uv_sync_flags = --package, tuf-on-ci, --frozen
changedir = repo
commands =
    python -m unittest

[testenv:test-signer]
description = Signer unit tests
labels = test
uv_sync_flags = --package, tuf-on-ci-sign, --frozen
changedir = signer
commands =
    python -m unittest

[testenv:test-e2e]
# See tests/README.md for the system dependencies
description = End-to-end tests with mocked GitHub Actions
labels = test
changedir = tests
commands =
    ./e2e.sh
