name: 'Snapshot & timestamp'
description: 'Produce new snapshot & timestamp versions if their content needs changing'

inputs:
  gcp_workload_identity_provider:
    description: 'Google Cloud workload identity provider'
    required: false
    default: ''
  gcp_service_account:
    description: 'Google Cloud service account name'
    required: false
    default: ''
  metadata_path:
    description: 'Path where to store the metadata files in the published repository'
    required: true
  targets_path:
    description: 'Path where to store the target files in the published repository'
    required: true

outputs:
  generated:
    # Currently always true: a repository artifact is published every time
    description: "'true' if a new repository version was uploaded"
    value: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      with:
        path: repository

    - name: Authenticate to Google Cloud
      if: inputs.gcp_workload_identity_provider != ''
      uses: google-github-actions/auth@35b0e87d162680511bf346c299f71c9c5c379033
      with:
        token_format: access_token
        workload_identity_provider: ${{ inputs.gcp_workload_identity_provider }}
        service_account: ${{ inputs.gcp_service_account }}

    - uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1
      with:
        python-version: "3.11"

    - run: pip install $GITHUB_ACTION_PATH/../../repo/
      shell: bash

    - id: snapshot
      run: |
        mkdir publish
        cd repository
        tuf-on-ci-snapshot --push --metadata ${{ inputs.metadata_path}} --targets ${{ inputs.targets_path}} ../publish

        find "../publish" -type f | xargs ls -lh
      shell: bash

    - name: Upload repository artifact for GitHub Pages
      uses: actions/upload-pages-artifact@a753861a5debcf57bf8b404356158c8e1e33150c
      with:
        path: publish/
