name: 'Signing event'
description: 'TUF-on-CI Signing event management'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        fetch-depth: 0

    - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236
      with:
        python-version: "3.11"

    - run: pip install $GITHUB_ACTION_PATH/../../repo/
      shell: bash

    - id: status
      run: |
        if tuf-on-ci-status >> status-output;  then
          echo "status=success" >> $GITHUB_OUTPUT
        else
          echo "status=failure" >> $GITHUB_OUTPUT
        fi
        cat status-output
        cat status-output >> "$GITHUB_STEP_SUMMARY"
      shell: bash

    - id: file-issue
      uses: actions/github-script@e69ef5462fd455e02edcaf4dd7708eda96b9eda0
      env:
        STATUS: ${{ steps.status.outputs.status }}
      with:
        script: |
          const fs = require('fs')
          message = fs.readFileSync('./status-output').toString()
          summary = ''

          issue = 0
          const repo = context.repo.owner + "/" + context.repo.repo
          const issues = await github.rest.search.issuesAndPullRequests({
            q: "label:" + process.env.GITHUB_REF_NAME + "+state:open+type:issue+repo:" + repo,
          })
          if (issues.data.total_count > 1) {
            core.setFailed("Found more than one issue with same label")
          } else if (issues.data.total_count == 0) {
            const response = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "Signing event: " + process.env.GITHUB_REF_NAME,
              body: "Processing signing event " + process.env.GITHUB_REF_NAME + ", please wait.",
              labels: [process.env.GITHUB_REF_NAME],
            })
            issue = response.data.number
            console.log("Created issue #" + issue)
          } else {
            issue = issues.data.items[0].number
            console.log("Found existing issue #" + issue)
          }

          if (process.env.STATUS == 'success') {
            pr_url = new URL("https://github.com/" + repo + "/compare/main..." + process.env.GITHUB_REF_NAME)
            pr_url.searchParams.set("expand", "1")
            pr_url.searchParams.set("title", "Signing event " + process.env.GITHUB_REF_NAME)
            pr_url.searchParams.set("body", "Signing event " + process.env.GITHUB_REF_NAME + " is successful and ready to merge.\n\nCloses #" + issue + ".")
            message += "### Signing event is successful\n\n"
            message += "Threshold of signatures has been reached. A [pull request](" + pr_url + ") can be opened."
            summary = "Signing event is successful"
          } else {
            summary = "Signing event in progress"
          }

          github.rest.issues.createComment({
            issue_number: issue,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: message,
          })

          await core.summary.addHeading(summary).write()
