name: 'Signing event'
description: 'TUF-on-CI Signing event management'

# This action is called from signing-event workflow, which is dispatched in multiple ways
# depending on the type of token provided in inputs.
#
# 1. create-signing-events action creates a new signing event branch
#     * When using a custom token this triggers push event handler
#     * When using the default GitHub token the action calls createWorkflowDispatch()
# 2. A signer pushes artifact changes to a signing event branch
#     * This triggers push event handler
# 3. This action (signing-event) makes a metadata change in update_targets step as a result of an artifact change
#     * When using a custom token this triggers push event handler
#     * When using the default GitHub token the action calls createWorkflowDispatch()
#
# Cases 1 & 3 lead to status step running. Case 2 leads to skipping status step, but
# triggering case 3 immediately afterwards.

inputs:
  token:
    description: 'GitHub token'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        token: ${{ inputs.token }}
        fetch-depth: 0

    - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c
      with:
        python-version: "3.11"

    - run: pip --quiet install $GITHUB_ACTION_PATH/../../repo/
      shell: bash

    - id: update_targets
      run: |
        if tuf-on-ci-update-targets >> status-output;  then
          echo "targets_updated=true" >> $GITHUB_OUTPUT
        else
          echo "targets_updated=false" >> $GITHUB_OUTPUT
        fi
        cat status-output
        cat status-output >> "$GITHUB_STEP_SUMMARY"
      shell: bash

    - id: status
      if: steps.update_targets.outputs.targets_updated != 'true'
      run: |
        if tuf-on-ci-status >> status-output;  then
          echo "status=success" >> $GITHUB_OUTPUT
        else
          echo "status=failure" >> $GITHUB_OUTPUT
        fi
        cat status-output
        cat status-output >> "$GITHUB_STEP_SUMMARY"
      shell: bash

    - id: update-pr
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
      env:
        STATUS: ${{ steps.status.outputs.status }}
      with:
        github-token: ${{ inputs.token }}
        script: |
          const fs = require('fs')
          const title = `Signing event: ${process.env.GITHUB_REF_NAME}`
          const repo = `${context.repo.owner}/${context.repo.repo}`
          const prs = await github.rest.search.issuesAndPullRequests({
            q: `in:title+"${title}"+state:open+type:pr+repo:${repo}`
          })

          if (prs.data.total_count > 1) {
            core.setFailed("Found more than one open pull request with same title")
          } else if (prs.data.total_count == 0) {
            const response = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: `Processing signing event ${process.env.GITHUB_REF_NAME}, please wait.`,
              draft: true,
              head: process.env.GITHUB_REF_NAME,
              base: "main",
            })
            pr = response.data.number
            console.log(`Created pull request #${pr}`)
          } else {
            pr = prs.data.items[0].number
            console.log(`Found existing pull request #${pr}`)
          }

          message = fs.readFileSync('./status-output').toString()
          if (process.env.STATUS == 'success') {
            message += "### Signing event is successful\n\n"
            message += "Threshold of signatures has been reached: this signing event can be reviewed and merged."
            summary = "Signing event is successful"
            should_be_draft = false
          } else {
            summary = "Signing event in progress"
            should_be_draft = true
          }

          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: pr,
            body: message,
          })

          // Following pile of GraphQL is here because draft state cannot
          // be modified through rest API at all!

          // First get the PR "Id" and current draft state...
          response = await github.graphql(`query {
            repository(owner: "${context.repo.owner}", name: "${context.repo.repo}") {
              pullRequest(number: ${pr}) { id, isDraft }
            }
          }`)
          pr_id = response.repository.pullRequest.id
          is_draft = response.repository.pullRequest.isDraft
          // Then modify PR if needed
          if (should_be_draft && !is_draft) {
            await github.graphql(`mutation SetPullRequestDraft {
              convertPullRequestToDraft(input: {pullRequestId: "${pr_id}"}) {
                pullRequest { isDraft }
              }
            }`)
          } else if (!should_be_draft && is_draft) {
            await github.graphql(`mutation SetPullRequestReady {
              markPullRequestReadyForReview(input: {pullRequestId: "${pr_id}"}) {
                pullRequest { isDraft }
              }
            }`)
          }

          await core.summary.addHeading(summary).write()

    - name: Dispatch another signing event workflow
      # dispatch if using default token: otherwise update_targets step has already triggered a push event
      if: inputs.token == github.token && steps.update_targets.outputs.targets_updated == 'true'
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
      with:
        github-token: ${{ inputs.token }}
        script: |
          console.log('Dispatching another signing event workflow after a targets metadata update')
          github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'signing-event.yml',
            ref: process.env.GITHUB_REF_NAME,
          })
