name: 'Upload Repository artifacts'
description: 'Build a publishable repository version and upload it as GitHub artifacts'

inputs:
  gh_pages:
    description: 'Upload a GitHub Pages compatible single artifact'
    required: false
    default: false
  metadata_path:
    description: 'Relative published metadata path (only useful with gh_pages)'
    required: false
    default: "metadata"
  artifacts_path:
    description: 'relative published artifact path (only useful with gh_pages)'
    required: false
    default: "targets"
  ref:
    description: 'Ref to clone'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        ref: ${{ inputs.ref }}

    - uses: actions/setup-python@b64ffcaf5b410884ad320a9cfac8866006a109aa
      with:
        python-version: "3.11"

    - run: pip install $GITHUB_ACTION_PATH/../../repo/
      shell: bash

    - id: build-repository
      run: |
        mkdir build
        tuf-on-ci-build-repository --metadata build/${{inputs.metadata_path}}  --artifacts build/${{inputs.artifacts_path}}

        find build -type f | xargs ls -lh
      shell: bash

    - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      if: inputs.gh_pages != 'true'
      with:
        name: metadata
        path: build/${{inputs.metadata_path}}/*

    - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      if: inputs.gh_pages != 'true'
      with:
        name: artifacts
        path: build/${{inputs.artifacts_path}}/*

    - uses: actions/upload-pages-artifact@a753861a5debcf57bf8b404356158c8e1e33150c # v2.0.0
      if: inputs.gh_pages == 'true'
      with:
        path: build/

    - id: status-summary
      shell: bash
      run: |
        if [ "${{inputs.gh_pages }}" == "true" ]; then
            echo "Repository is uploaded and ready to be deployed to GitHub Pages" >> $GITHUB_STEP_SUMMARY
        else
            echo "Repository is uploaded to artifacts" >> $GITHUB_STEP_SUMMARY
        fi
