name: 'Upload Repository artifacts'
description: 'Build a publishable repository version and upload it as GitHub artifacts'

inputs:
  gh_pages:
    description: 'Upload a GitHub Pages compatible single artifact'
    required: false
    default: false
  metadata_path:
    description: 'Relative published metadata path (only useful with gh_pages)'
    required: false
    default: "metadata"
  artifacts_path:
    description: 'relative published artifact path (only useful with gh_pages)'
    required: false
    default: "targets"
  ref:
    description: 'Ref to clone'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        ref: ${{ inputs.ref }}
        persist-credentials: false

    - uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
      with:
        python-version: "3.14"

    - run: |
        echo "::group::Install tuf-on-ci"
        ROOT=$GITHUB_ACTION_PATH/../..
        pip install -c $ROOT/action-constraints.txt $ROOT/repo/
        echo "::endgroup::"
      shell: bash

    - id: build-repository
      env:
        METADATA_PATH: ${{inputs.metadata_path}}
        ARTIFACTS_PATH: ${{inputs.artifacts_path}}
      run: |
        mkdir build
        tuf-on-ci-build-repository --metadata "build/$METADATA_PATH"  --artifacts "build/$ARTIFACTS_PATH"

        find build -type f | xargs ls -lh
      shell: bash

    - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      if: inputs.gh_pages != 'true'
      with:
        name: metadata
        path: build/${{inputs.metadata_path}}/*

    - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      if: inputs.gh_pages != 'true'
      with:
        name: artifacts
        path: build/${{inputs.artifacts_path}}/*

    - uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
      if: inputs.gh_pages == 'true'
      with:
        path: build/

    - id: status-summary
      shell: bash
      env:
        GH_PAGES: ${{inputs.gh_pages}}
      run: |
        if [ "$GH_PAGES" == "true" ]; then
            echo "Repository is uploaded and ready to be deployed to GitHub Pages" >> $GITHUB_STEP_SUMMARY
        else
            echo "Repository is uploaded to artifacts" >> $GITHUB_STEP_SUMMARY
        fi
