name: 'Upload Repository artifacts'
description: 'Build a publishable repository version and upload it as GitHub artifacts'

inputs:
  gh_pages:
    description: 'Upload a GitHub Pages compatible single artifact'
    required: false
    default: false
  metadata_path:
    description: 'Relative published metadata path (only useful with gh_pages)'
    required: false
    default: "metadata"
  artifacts_path:
    description: 'relative published artifact path (only useful with gh_pages)'
    required: false
    default: "targets"
  ref:
    description: 'Ref to clone'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        ref: ${{ inputs.ref }}

    - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
      with:
        python-version: "3.11"

    - run: |
        echo "::group::Install tuf-on-ci"
        ROOT=$GITHUB_ACTION_PATH/../..
        pip install -c $ROOT/action-constraints.txt $ROOT/repo/
        cp $GITHUB_ACTION_PATH/index.css .
        echo "::endgroup::"
      shell: bash

    - id: build-repository
      env:
        METADATA_PATH: ${{inputs.metadata_path}}
        ARTIFACTS_PATH: ${{inputs.artifacts_path}}
      run: |
        mkdir build
        tuf-on-ci-build-repository --metadata "build/$METADATA_PATH"  --artifacts "build/$ARTIFACTS_PATH"

        find build -type f | xargs ls -lh
      shell: bash

    - name: Render repository state in HTML
      uses: docker://pandoc/core:3.5.0@sha256:771842ce6f661785e0e12931f82ea64046d70fa48ea5cff480492d79ab3b8ff1
      with:
        args: >-
          --metadata title="TUF Repository state"
          --variable title=""
          --standalone
          --embed-resources
          --css index.css
          --output build/${{inputs.metadata_path}}/index.html
          build/${{inputs.metadata_path}}/index.md

    - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
      if: inputs.gh_pages != 'true'
      with:
        name: metadata
        path: build/${{inputs.metadata_path}}/*

    - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
      if: inputs.gh_pages != 'true'
      with:
        name: artifacts
        path: build/${{inputs.artifacts_path}}/*

    - uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
      if: inputs.gh_pages == 'true'
      with:
        path: build/

    - id: status-summary
      shell: bash
      env:
        GH_PAGES: ${{inputs.gh_pages}}
      run: |
        if [ "$GH_PAGES" == "true" ]; then
            echo "Repository is uploaded and ready to be deployed to GitHub Pages" >> $GITHUB_STEP_SUMMARY
        else
            echo "Repository is uploaded to artifacts" >> $GITHUB_STEP_SUMMARY
        fi
