name: 'Upload Repository artifacts'
description: 'Build a publishable repository version and upload it as GitHub artifacts'

inputs:
  gh_pages:
    description: 'Upload a GitHub Pages compatible single artifact'
    required: false
    default: false
  metadata_path:
    description: 'Relative published metadata path (only useful with gh_pages)'
    required: false
    default: "metadata"
  artifacts_path:
    description: 'relative published artifact path (only useful with gh_pages)'
    required: false
    default: "targets"
  ref:
    description: 'Ref to clone'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        ref: ${{ inputs.ref }}
        persist-credentials: false

    - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
      with:
        python-version: "3.14"

    - run: |
        echo "::group::Install tuf-on-ci"
        ROOT=$GITHUB_ACTION_PATH/../..
        pip install -c $ROOT/action-constraints.txt $ROOT/repo/
        cp $GITHUB_ACTION_PATH/index.css .
        echo "::endgroup::"
      shell: bash

    - id: build-repository
      env:
        METADATA_PATH: ${{inputs.metadata_path}}
        ARTIFACTS_PATH: ${{inputs.artifacts_path}}
      run: |
        mkdir build
        tuf-on-ci-build-repository --metadata "build/$METADATA_PATH"  --artifacts "build/$ARTIFACTS_PATH"

        find build -type f | xargs ls -lh
      shell: bash

    - name: Render repository state in HTML
      uses: docker://pandoc/core:3.5.0@sha256:befd63aa7c9b795bdf681415e3984aaa2fe20eeed3b5facca494f125f4171218
      with:
        args: >-
          --metadata title="TUF Repository state"
          --variable title=""
          --standalone
          --embed-resources
          --css index.css
          --output build/${{inputs.metadata_path}}/index.html
          build/${{inputs.metadata_path}}/index.md

    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      if: inputs.gh_pages != 'true'
      with:
        name: metadata
        path: build/${{inputs.metadata_path}}/*

    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      if: inputs.gh_pages != 'true'
      with:
        name: artifacts
        path: build/${{inputs.artifacts_path}}/*

    - uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
      if: inputs.gh_pages == 'true'
      with:
        path: build/

    - id: status-summary
      shell: bash
      env:
        GH_PAGES: ${{inputs.gh_pages}}
      run: |
        if [ "$GH_PAGES" == "true" ]; then
            echo "Repository is uploaded and ready to be deployed to GitHub Pages" >> $GITHUB_STEP_SUMMARY
        else
            echo "Repository is uploaded to artifacts" >> $GITHUB_STEP_SUMMARY
        fi
