name: 'Upload Repository artifacts'
description: 'Build a publishable repository version and upload it as GitHub artifacts'

inputs:
  gh_pages:
    description: 'Upload a GitHub Pages compatible single artifact'
    required: false
    default: false
  metadata_path:
    description: 'Relative published metadata path (only useful with gh_pages)'
    required: false
    default: "metadata"
  artifacts_path:
    description: 'relative published artifact path (only useful with gh_pages)'
    required: false
    default: "targets"
  ref:
    description: 'Ref to clone'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      with:
        ref: ${{ inputs.ref }}

    - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
      with:
        python-version: "3.11"

    - run: |
        echo "::group::Install tuf-on-ci"
        REPO=$GITHUB_ACTION_PATH/../../repo/
        pip install -c $REPO/install/requirements.txt $REPO
        echo "::endgroup::"
      shell: bash

    - id: build-repository
      run: |
        mkdir build
        tuf-on-ci-build-repository --metadata build/${{inputs.metadata_path}}  --artifacts build/${{inputs.artifacts_path}}

        find build -type f | xargs ls -lh
      shell: bash

    - uses: actions/jekyll-build-pages@b178f9334b208360999a0a57b523613563698c66 # 1.0.12
      with:
        source: build
        destination: build-jekyll

    - uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
      if: inputs.gh_pages != 'true'
      with:
        name: metadata
        path: build-jekyll/${{inputs.metadata_path}}/*

    - uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
      if: inputs.gh_pages != 'true'
      with:
        name: artifacts
        path: build-jekyll/${{inputs.artifacts_path}}/*

    - uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
      if: inputs.gh_pages == 'true'
      with:
        path: build-jekyll/

    - id: status-summary
      shell: bash
      run: |
        if [ "${{inputs.gh_pages }}" == "true" ]; then
            echo "Repository is uploaded and ready to be deployed to GitHub Pages" >> $GITHUB_STEP_SUMMARY
        else
            echo "Repository is uploaded to artifacts" >> $GITHUB_STEP_SUMMARY
        fi
