name: 'Upload Repository artifacts'
description: 'Build a publishable repository version and upload it as GitHub artifacts'

inputs:
  gh_pages:
    description: 'Upload a GitHub Pages compatible single artifact'
    required: false
    default: false
  metadata_path:
    description: 'Relative published metadata path (only useful with gh_pages)'
    required: false
    default: "metadata"
  artifacts_path:
    description: 'relative published artifact path (only useful with gh_pages)'
    required: false
    default: "targets"
  ref:
    description: 'Ref to clone'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      with:
        ref: ${{ inputs.ref }}

    - uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
      with:
        python-version: "3.11"

    - run: |
        echo "::group::Install tuf-on-ci"
        ROOT=$GITHUB_ACTION_PATH/../..
        pip install -c $ROOT/action-constraints.txt $ROOT/repo/
        echo "::endgroup::"
      shell: bash

    - id: build-repository
      run: |
        mkdir build
        tuf-on-ci-build-repository --metadata build/${{inputs.metadata_path}}  --artifacts build/${{inputs.artifacts_path}}

        find build -type f | xargs ls -lh
      shell: bash

    - uses: actions/jekyll-build-pages@44a6e6beabd48582f863aeeb6cb2151cc1716697 # 1.0.13
      with:
        source: build
        destination: build-jekyll

    - uses: actions/upload-artifact@604373da6381bf24206979c74d06a550515601b9 # v4.4.1
      if: inputs.gh_pages != 'true'
      with:
        name: metadata
        path: build-jekyll/${{inputs.metadata_path}}/*

    - uses: actions/upload-artifact@604373da6381bf24206979c74d06a550515601b9 # v4.4.1
      if: inputs.gh_pages != 'true'
      with:
        name: artifacts
        path: build-jekyll/${{inputs.artifacts_path}}/*

    - uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
      if: inputs.gh_pages == 'true'
      with:
        path: build-jekyll/

    - id: status-summary
      shell: bash
      run: |
        if [ "${{inputs.gh_pages }}" == "true" ]; then
            echo "Repository is uploaded and ready to be deployed to GitHub Pages" >> $GITHUB_STEP_SUMMARY
        else
            echo "Repository is uploaded to artifacts" >> $GITHUB_STEP_SUMMARY
        fi
