[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"

[project]
name = "tuf-on-ci-sign"
version = "0.20.0"
description = "Signing tools for TUF-on-CI"
license = "MIT"
license-files = [ "LICENSE" ]
readme = "README.md"
dependencies = [
  "packaging >= 24",
  "platformdirs >= 4.2",
  "securesystemslib[awskms,azurekms,gcpkms,hsm,sigstore] >= 1.2",
  "tuf >= 5.1",
  "click >= 8.1",
]
requires-python = ">=3.9"

[project.urls]
issues = "https://github.com/theupdateframework/tuf-on-ci/issues"
source = "https://github.com/theupdateframework/tuf-on-ci/"

[project.scripts]
tuf-on-ci-delegate = "tuf_on_ci_sign:delegate"
tuf-on-ci-import-repo = "tuf_on_ci_sign:import_repo"
tuf-on-ci-sign = "tuf_on_ci_sign:sign"

[tool.mypy]
python_version = "3.10"

