name: "Online sign"
description: "Creates a snapshot and timestamp if needed, moves publish branch if needed"

inputs:
  token:
    description: 'GitHub token'
    required: true
  gcp_workload_identity_provider:
    description: "Google Cloud workload identity provider"
    required: false
    default: ""
  gcp_service_account:
    description: "Google Cloud service account name"
    required: false
    default: ""
  aws_region:
    description: "AWS region"
    required: false
    default: ""
  aws_role_to_assume:
    description: "AWS role to assume"
    required: false
    default: ""
  azure_client_id:
    description: "Azure SPN client id (required to use Azure to sign target roles)"
    required: false
    default: ""
  azure_tenant_id:
    description: "Azure SPN tenant id (required to use Azure to sign target roles)"
    required: false
    default: ""
  azure_subscription_id:
    description: "Azure SPN subscription id (required to use Azure to sign target roles)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        token: ${{ inputs.token }}
        fetch-depth: 0
        persist-credentials: true


    - name: Authenticate to Google Cloud
      if: inputs.gcp_workload_identity_provider != ''
      uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
      with:
        token_format: access_token
        workload_identity_provider: ${{ inputs.gcp_workload_identity_provider }}
        service_account: ${{ inputs.gcp_service_account }}

    - name: Authenticate to AWS
      if: inputs.aws_role_to_assume != ''
      uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 #v5.1.1
      with:
        aws-region: ${{ inputs.aws_region }}
        role-to-assume: ${{ inputs.aws_role_to_assume }}

    - name: Authenticate to Azure cloud
      if: inputs.azure_client_id != ''
      uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
      with:
        client-id: ${{ inputs.azure_client_id }}
        tenant-id: ${{ inputs.azure_tenant_id }}
        subscription-id: ${{ inputs.azure_subscription_id }}

    - uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
      with:
        python-version: "3.14"

    - run: |
        echo "::group::Install tuf-on-ci"
        ROOT=$GITHUB_ACTION_PATH/../..
        pip install -c $ROOT/action-constraints.txt $ROOT/repo/
        echo "::endgroup::"
      shell: bash

    - id: online-sign
      run: |
        tuf-on-ci-online-sign --push

        # did we actually create a snapshot/timestamp commit?
        if [[ $GITHUB_SHA == $(git rev-parse HEAD) ]]; then
          echo "ONLINE_SIGNED=false"
          echo "ONLINE_SIGNED=false" >> "$GITHUB_ENV"
          echo "### Nothing to sign" >> "$GITHUB_STEP_SUMMARY"
        else
          echo "ONLINE_SIGNED=true"
          echo "ONLINE_SIGNED=true" >> "$GITHUB_ENV"
        fi
      shell: bash

    - id: move-publish-branch
      if: github.event_name != 'schedule' || env.ONLINE_SIGNED == 'true'
      run: |
        git show --oneline --no-patch HEAD
        git push origin HEAD:publish
        echo "rev=`git rev-parse HEAD`" >> $GITHUB_OUTPUT
        echo "### Online signing finished, will now publish" >> $GITHUB_STEP_SUMMARY
      shell: bash

    - id: dispatch-publish-workflow
      if: github.event_name != 'schedule' || env.ONLINE_SIGNED == 'true'
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      env:
        REV: ${{ steps.move-publish-branch.outputs.rev }}
      with:
        github-token: ${{ inputs.token }}
        script: |
          console.log('Dispatching publish workflow')
          github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'publish.yml',
            ref: 'publish',
            inputs: {
              ref: process.env.REV,
            },
          })
