name: "Online sign"
description: "Creates a snapshot and timestamp if needed, moves publish branch if needed"

inputs:
  token:
    description: 'GitHub token'
    required: true
  gcp_workload_identity_provider:
    description: "Google Cloud workload identity provider"
    required: false
    default: ""
  gcp_service_account:
    description: "Google Cloud service account name"
    required: false
    default: ""
  aws_region:
    description: "AWS region"
    required: false
    default: ""
  aws_role_to_assume:
    description: "AWS role to assume"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      with:
        token: ${{ inputs.token }}
        fetch-depth: 0

    - name: Authenticate to Google Cloud
      if: inputs.gcp_workload_identity_provider != ''
      uses: google-github-actions/auth@55bd3a7c6e2ae7cf1877fd1ccb9d54c0503c457c # v2.1.2
      with:
        token_format: access_token
        workload_identity_provider: ${{ inputs.gcp_workload_identity_provider }}
        service_account: ${{ inputs.gcp_service_account }}

    - name: Authenticate to AWS
      if: inputs.aws_role_to_assume != ''
      uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 #v4.0.2
      with:
        aws-region: ${{ inputs.aws_region }}
        role-to-assume: ${{ inputs.aws_role_to_assume }}

    - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
      with:
        python-version: "3.11"

    - run: |
        echo "::group::Install tuf-on-ci"
        pip install $GITHUB_ACTION_PATH/../../repo/
        echo "::endgroup::"
      shell: bash

    - id: online-sign
      run: |
        tuf-on-ci-online-sign --push

        # did we actually create a snapshot/timestamp commit?
        if [[ $GITHUB_SHA == $(git rev-parse HEAD) ]]; then
          echo "ONLINE_SIGNED=false"
          echo "ONLINE_SIGNED=false" >> "$GITHUB_ENV"
          echo "### Nothing to sign" >> "$GITHUB_STEP_SUMMARY"
        else
          echo "ONLINE_SIGNED=true"
          echo "ONLINE_SIGNED=true" >> "$GITHUB_ENV"
        fi
      shell: bash

    - id: move-publish-branch
      if: github.event_name != 'schedule' || env.ONLINE_SIGNED == 'true'
      run: |
        git show --oneline --no-patch HEAD
        git push origin HEAD:publish
        echo "rev=`git rev-parse HEAD`" >> $GITHUB_OUTPUT
        echo "### Online signing finished, will now publish" >> $GITHUB_STEP_SUMMARY
      shell: bash

    - id: dispatch-publish-workflow
      if: github.event_name != 'schedule' || env.ONLINE_SIGNED == 'true'
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        github-token: ${{ inputs.token }}
        script: |
          console.log('Dispatching publish workflow')
          github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'publish.yml',
            ref: 'publish',
            inputs: {
              ref: '${{ steps.move-publish-branch.outputs.rev }}',
            },
          })
