name: 'Create signing events'
description: 'Create signing events for offline signed metadata that is about to expire'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      with:
        fetch-depth: 0

    - uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1
      with:
        python-version: "3.11"

    - run: pip install $GITHUB_ACTION_PATH/../../repo/
      shell: bash

    - name: Bump offline role versions
      id: offline-bump
      run: |
        events=$(tuf-on-ci-bump-offline --push)
        echo events="$events"
        echo events="$events" >> $GITHUB_OUTPUT
      shell: bash

    - name: Dispatch signing events
      if: steps.offline-bump.outputs.events != ''
      env:
        EVENTS: ${{ steps.offline-bump.outputs.events }}
      uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410
      with:
        script: |
          console.log('Dispatching events: ', process.env.EVENTS)
          process.env.EVENTS.trim().split(' ').forEach(event => {
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'signing-event.yml',
              ref: event,
            })
          })
