name: 'Create signing events'
description: 'Create signing events for offline signed metadata that is about to expire'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        fetch-depth: 0

    - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236
      with:
        python-version: "3.11"

    - run: pip install $GITHUB_ACTION_PATH/../../repo/
      shell: bash

    - name: Create signing event branches for expiring roles
      id: create-signing-events
      run: |
        events=$(tuf-on-ci-create-signing-events --push)
        echo events="$events"
        echo events="$events" >> $GITHUB_OUTPUT
        if [ -z "${events}" ]; then
            echo "Nothing to prepare" >> $GITHUB_STEP_SUMMARY
        else
            echo "Dispatching events for ${events}" >> $GITHUB_STEP_SUMMARY
        fi
      shell: bash

    - name: Dispatch signing event workflow
      if: steps.create-signing-events.outputs.events != ''
      env:
        EVENTS: ${{ steps.create-signing-events.outputs.events }}
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
      with:
        script: |
          console.log('Dispatching events: ', process.env.EVENTS)
          process.env.EVENTS.trim().split(' ').forEach(event => {
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'signing-event.yml',
              ref: event,
            })
          })
