name: Lint actions & workflows

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  lint-actions-and-workflows:
    name: Lint actions & workflows
    permissions:
      security-events: write
      contents: read
      actions: read
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      with:
        python-version: '3.14'
        enable-cache: true
        cache-dependency-glob: |
          actions/lint-requirements.txt

    - name: Install zizmor
      run: uv tool install zizmor -c actions/lint-requirements.txt

    - name: Run zizmor
      run: zizmor .
