name: Lint & test

on:
  push:
    branches: [main]
  pull_request:

permissions: {}

jobs:
  test:
    name: Lint & test
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        toxenv: [lint-signer, test-signer]
        pyversion: ['3.10', '3.14']
        os: [ubuntu-latest, macos-latest]
        # Only run repository on 3.14 (dependency pinning is easier with single version)
        include:
          - toxenv: lint-repo
            pyversion: '3.14'
            os: ubuntu-latest
          - toxenv: test-repo
            pyversion: '3.14'
            os: ubuntu-latest
          - toxenv: test-e2e
            pyversion: '3.14'
            os: ubuntu-latest
          - toxenv: lint-actions
            pyversion: '3.14'
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    env:
      TOXENV: ${{ matrix.toxenv }}

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      with:
        python-version: ${{ matrix.pyversion }}
        enable-cache: true
        version-file: pyproject.toml
        cache-dependency-glob: |
          signer/pyproject.toml
          repo/pyproject.toml
          uv.lock

    - name: Install system dependencies for e2e test
      if: matrix.toxenv == 'test-e2e'
      run: |
        sudo apt-get install libfaketime softhsm2
        echo "PYKCS11LIB=/usr/lib/softhsm/libsofthsm2.so" >> $GITHUB_ENV

    - name: ${{ matrix.toxenv }}
      run: make $TOXENV

    - name: Print tox env contents
      run: uv pip tree --python .tox/$TOXENV


