name: Lint & test

on:
  push:
    branches: [main]
  pull_request:

permissions: {}

jobs:
  test:
    name: Lint & test
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        target: [test-signer]
        pyversion: ['3.10', '3.14']
        os: [ubuntu-latest, macos-latest]
        # Only run repository on 3.14 (dependency pinning is easier with single version)
        include:
          - target: lint-signer
            pyversion: '3.14'
            os: ubuntu-latest
          - target: lint-repo
            pyversion: '3.14'
            os: ubuntu-latest
          - target: test-repo
            pyversion: '3.14'
            os: ubuntu-latest
          - target: test-e2e
            pyversion: '3.14'
            os: ubuntu-latest
          - target: lint-actions
            pyversion: '3.14'
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    env:
      TARGET: ${{ matrix.target }}

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - uses: astral-sh/setup-uv@ae62891fec2bb8e7d6c99fc78c9fec3a63790f8d # v10.0.0
      with:
        python-version: ${{ matrix.pyversion }}
        enable-cache: true
        version-file: uv.lock
        cache-dependency-glob: |
          signer/pyproject.toml
          repo/pyproject.toml
          uv.lock

    - name: Install system dependencies for e2e test
      if: matrix.target == 'test-e2e'
      run: |
        sudo apt-get install libfaketime softhsm2
        echo "PYKCS11LIB=/usr/lib/softhsm/libsofthsm2.so" >> $GITHUB_ENV

    - name: ${{ matrix.target }}
      run: make $TARGET


